// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD91UT4Hjv9Yb71qPX2E_4TsgDhN4JI-sw',
    appId: '1:138532362750:web:554156c0a1c5995d86c8af',
    messagingSenderId: '138532362750',
    projectId: 'firebase-stuntfree',
    authDomain: 'fir-stuntfree.firebaseapp.com',
    storageBucket: 'firebase-stuntfree.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8C7tL-U1Cy_-4nYCb_beqrfr-UCX3mC0',
    appId: '1:138532362750:android:e9ea27af32f2d6de86c8af',
    messagingSenderId: '138532362750',
    projectId: 'firebase-stuntfree',
    storageBucket: 'firebase-stuntfree.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC06tBHzUsMN7rXajD-a97tkK-9N1mUeHE',
    appId: '1:138532362750:ios:a205d1e4a1b5087886c8af',
    messagingSenderId: '138532362750',
    projectId: 'firebase-stuntfree',
    storageBucket: 'firebase-stuntfree.firebasestorage.app',
    iosBundleId: 'com.example.stuntfreeMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC06tBHzUsMN7rXajD-a97tkK-9N1mUeHE',
    appId: '1:138532362750:ios:a205d1e4a1b5087886c8af',
    messagingSenderId: '138532362750',
    projectId: 'firebase-stuntfree',
    storageBucket: 'firebase-stuntfree.firebasestorage.app',
    iosBundleId: 'com.example.stuntfreeMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD91UT4Hjv9Yb71qPX2E_4TsgDhN4JI-sw',
    appId: '1:138532362750:web:99b470ceabc51a1a86c8af',
    messagingSenderId: '138532362750',
    projectId: 'firebase-stuntfree',
    authDomain: 'fir-stuntfree.firebaseapp.com',
    storageBucket: 'firebase-stuntfree.firebasestorage.app',
  );
}
